### ISSUE TITLE
Cannot read a simple file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sanblch/parf#1]
```
Does not even read a simple file. File is attached.

./parf -t file1.arff 
forrtl: severe (24): end-of-file during read, unit -5, file Internal 
List-Directed Read



```

Original issue reported on code.google.com by `s.sa...@gmail.com` on 10 Jun 2010 at 12:29

Attachments:
* [file1.arff](https://storage.googleapis.com/google-code-attachments/parf/issue-1/comment-0/file1.arff)

**Comment by sanblch** [comment]
Compiled with ifort version is working normal, when [arff](https://github.com/sanblch/parf/files/175854/harddrive1_train.arff.tar.gz) is correctly formed.

`./parf --verbose -t harddrive1_train.arff`
