### ISSUE TITLE
'make' command for installing parf not working; even after changing default compiler

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sanblch/parf#3]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `svtydeek...@gmail.com` on 5 Aug 2014 at 4:42

**Comment by sanblch** [comment]
Ubuntu 14.04 LTS, mpich2 custom build.

1. ifort
2. gfortran-5.2.0
3. mpif90-3.2

were tested and added to Makefile. See the [commit](https://github.com/sanblch/parf/commit/90ab10bc9fc61ddab8ec619952ba1d690a157f65).
